name: conditionals-issues!
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: handle-all-issues
        run: echo "This step runs for all issues"
      - if: startsWith(github.event.issue.title, 'bug')
        name: handle-bug-reports
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"body":"Hello ${{ github.event.issue.user.login }}, thanks for reporting the bug!"}'
      - if: startsWith(github.event.issue.title, 'feature request')
        name: handle-feature-requests
        run: echo "This step runs only for feature requests"
